### ISSUE TITLE
Story : R05 - Studio | Listener & Guest profiles

### ISSUE THREAD

**Issue by ManZzup** [findnedl/nedl#2]
Story Name
=========

Implement the listener and host profiles

**Tasks**
- [ ] Listener profile in Studio
- [ ] Host profile in Studio
- [ ] Listener profile in audience
- [ ] Host profile in audience

**Workflows**
Link any Miro frames for workflows.

**UI/UX**
Link Figma/Avocode or upload attachments.

**Assumptions & Decisions**
Keep this section updated while the project is progressing.
