### ISSUE TITLE
Story : Audience | Enable voices

### ISSUE THREAD

**Issue by ManZzup** [findnedl/nedl#3]
Story Name
=========

Enable the Voices in the audience app

**Tasks**
- [ ] Show Voices in explore
- [ ] Show Voices in search
- [ ] Show Voices in live transcript search

You can convert each task to an issue later on.

**Workflows**
Link any Miro frames for workflows.

**UI/UX**
Link Figma/Avocode or upload attachments.

**Assumptions & Decisions**
Keep this section updated while the project is progressing.
